name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip project
        run: unzip Dropix1.zip
        
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          
      - name: Build APK
        run: cd $(ls -d */ | head -n 1) && flutter pub get && flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dropix-apk
          path: '*/build/app/outputs/flutter-apk/app-release.apk'
